from std.testing import assert_equal, assert_false, assert_true
from tsonic_node.readline.lines import LineBuffer


def main() raises:
    var lines = LineBuffer()
    lines.feed("first\r")
    lines.feed("\n\nsecond\rthird\nfourth😀")
    var first = lines.take().value().copy()
    assert_equal(first.text, "first")
    assert_true(first.terminated)
    assert_equal(lines.take().value().text, "")
    assert_equal(lines.take().value().text, "second")
    assert_equal(lines.take().value().text, "third")
    assert_false(Bool(lines.take()))
    assert_equal(lines.current, "fourth😀")
    assert_equal(lines.cursor(), 8)
    lines.finish()
    lines.finish()
    assert_true(lines.has_lines())
    var tail = lines.take().value().copy()
    assert_equal(tail.text, "fourth😀")
    assert_false(tail.terminated)
    assert_false(lines.has_lines())
    assert_false(Bool(lines.take()))
    lines = LineBuffer()
    lines.feed("one\ntwo\n")
    lines.finish()
    assert_equal(lines.take().value().text, "one")
    assert_equal(lines.take().value().text, "two")
    assert_false(Bool(lines.take()))
    lines = LineBuffer()
    lines.feed("\r\r\n")
    assert_equal(lines.take().value().text, "")
    assert_equal(lines.take().value().text, "")
    assert_false(Bool(lines.take()))
    lines = LineBuffer()
    lines.feed("pending\npartial")
    lines.clear()
    assert_false(Bool(lines.take()))
    assert_equal(lines.current, "partial")
