from std.testing import assert_equal, assert_false
from tsonic_node.readline.lines import LineBuffer


def main() raises:
    var lines = LineBuffer()
    lines.feed("first\r")
    lines.feed("\n\nsecond\rthird\nfourth😀")
    assert_equal(lines.take().value(), "first")
    assert_equal(lines.take().value(), "")
    assert_equal(lines.take().value(), "second")
    assert_equal(lines.take().value(), "third")
    assert_false(Bool(lines.take()))
    assert_equal(lines.current, "fourth😀")
    assert_equal(lines.cursor(), 8)
    lines.finish()
    lines.finish()
    assert_equal(lines.take().value(), "fourth😀")
    assert_false(Bool(lines.take()))
    lines = LineBuffer()
    lines.feed("one\ntwo\n")
    lines.finish()
    assert_equal(lines.take().value(), "one")
    assert_equal(lines.take().value(), "two")
    assert_false(Bool(lines.take()))
    lines = LineBuffer()
    lines.feed("\r\r\n")
    assert_equal(lines.take().value(), "")
    assert_equal(lines.take().value(), "")
    assert_false(Bool(lines.take()))
    lines = LineBuffer()
    lines.feed("pending\npartial")
    lines.clear()
    assert_false(Bool(lines.take()))
    assert_equal(lines.current, "partial")
